### ISSUE TITLE
Add translations for other languages

### ISSUE THREAD

**Issue by rezemika** [rezemika/humanized_opening_hours#13]
Currently, only english and french are supported for rendering. It would be great if HOH support other languages. So, if there's any language that you would like to see HOH work with, please don't hesitate to create a pull request! :)

To add a new translation:

- add its locale name in `AVAILABLE_LOCALES` in `rendering.py`;
- go to the `humanized_opening_hours` folder;
- create a folder for you translation: `mkdir -p locales/<LOCALE>/LC_MESSAGES` (replace `<LOCALE>` with the name of the locale);
- create a new POT file with : `xgettext -o locales/<LOCALE>/LC_MESSAGES/hoh.pot temporal_objects.py rendering.py`;
- update this new file to add translations;
- compile it to a MO file with `msgfmt -o locales/<LOCALE>/LC_MESSAGES/hoh.mo locales/fr_FR/LC_MESSAGES/hoh.pot`;
- test the rendering of some fields with you new locale.

Thank you!

**Comment by fklement** [comment]
Hello, wanted to add a new translation for german.  
Only got one problem:
When i execute `xgettext -o locales/de/LC_MESSAGES/hoh.pot temporal_objects.py rendering.py` i'm getting this error:  
`xgettext: Ausgabedatei »locales/de/LC_MESSAGES/hoh.pot« kann nicht erstellt werden: No such file or directory`

**Comment by fklement** [comment]
I tried it from there.

**Comment by rezemika** [comment]
Oh ok, so I was wrong concerning the `xgettext` command. Can you try a `mkdir -p locales/de/LC_MESSAGES`?

**Comment by sashman** [comment]
@rezemika exactly what I had to do, the directory must exist first

**Comment by fklement** [comment]
Ahh. Works!  
Could have figured it out for myself.

**Comment by rezemika** [comment]
Okay, thank you! Sorry for the mistake.

**Comment by fklement** [comment]
No problem!
