### ISSUE TITLE
Améliorer et vérifier la documentation

### ISSUE THREAD

**Issue by rezemika** [rezemika/humanized_opening_hours#2]
Il y a quelques imprécisions dans le README et les docstrings. Il faudrait harmoniser et corriger tout cela.

Aussi, il y a une petite erreur dans le README.

```python
>>> import humanized_opening_hours
>>> field = "Mo-Fr 06:00-21:00; Sa,Su 07:00-21:00"
>>> hoh = HumanizedOpeningHours(field)  # Devrait être "humanized_opening_hours.HumanizedOpeningHours(field)"
[...]
```

**Comment by knil-sama** [comment]
Salut, je serais bien interessé pour faire cela, est ce que la convention [napoleon](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) te convient pour les docstring ?

**Comment by rezemika** [comment]
Pourquoi pas. Jusqu'à présent, je suivais la convention [numpy](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html), mais je suis ouvert à d'autres choses. :)

**Comment by knil-sama** [comment]
Bon je reste sur numpy dans ce cas là, je pense sortir la pour jeudi.

**Comment by knil-sama** [comment]
#4 pull request a valider
