### ISSUE TITLE
Can't parse comma-separated ranges

### ISSUE THREAD

**Issue by nbolten** [rezemika/humanized_opening_hours#7]
OHParser raises a ParseError on day ranges after a comma: 
```
hoh.OHParser('We,Fr-Su 10:00-17:00')
```

`ParseError: The field could not be parsed, it may be invalid. Error happened on column 5 when parsing '-'.`

This error doesn't happen if you have the range first: `hoh.OHParser('We-Fr,Su 10:00-17:00')`

I've opened a pull request at #6, but since I'm new to EBNF it probably contains some issues.

**Comment by rezemika** [comment]
This will be fixed with the 1.0.0 coming soon version. ;)
