### ISSUE TITLE
Avoid sys.path[0] for finding setup.py directory

### ISSUE THREAD

**Issue by nbolten** [rezemika/humanized_opening_hours#8]
I wanted to use a fork (temporarily), and found that the default `setup.py` fails on my system (Python 3.5, Ubuntu 16.04) as it uses `sys.path[0]` in an attempt to find the development directory. I assume this is because the main dev environment involves prepending to $PYTHONPATH. However, this makes the package non-portable - `system.path[0]` is set to `''` by default, so `setup.py` raises a `FileNotFoundError` when attempting to change to that directory.

To indicate the directory of `setup.py`, use `__file__`:

`os.path.chdir(os.path.dirname(os.path.realpath(__file__)))`

**Comment by rezemika** [comment]
Done by 350973d (I used a `BASE_DIR` variable). Can you confirm it works?

Thank you! :)

**Comment by nbolten** [comment]
## The solution in commit 350973d

Hey! Your solution is better because it avoids running `os.chdir` at all.

It does have a redundant `os.path.dirname` though, just a heads up.

## Other remaining impacts

`main.py` still runs `os.chdir`, and it's messing up my scripts because it changes the meaning of `__file__` somehow, or something like that. So far as I can tell, its purpose is to make it so that `field_parser.py` can find the .ebnf file. I think this would fix it:

1. Delete this line in `main.py`:

`os.chdir(os.path.dirname(os.path.realpath(__file__)))`

2. Edit this line in `field_parser.py`:

From:
```
    base_dir = os.path.realpath(os.path.join(
        os.getcwd(), os.path.dirname(__file__)
    ))
```

To:
```
    base_dir = is.path.dirname(os.path.realpath(__file__))
```

**Comment by rezemika** [comment]
Thank you! Done with a1bdc6e, can you confirm (again) please?

**Comment by rezemika** [comment]
Ping @nbolten. ;)
